---
- name: Install and start Jenkins
  hosts: jenkins_server
  become: true
  tasks:
    - name: Install Java
      ansible.builtin.dnf:
        name: java-1.8.0-openjdk
        state: present

    - name: Add Jenkins repository key
      ansible.builtin.rpm_key:
        url: https://pkg.jenkins.io/redhat/jenkins.io.key
        state: present
        key: https://pkg.jenkins.io/redhat/jenkins.io.key  # Key added here

    - name: Add Jenkins repository
      ansible.builtin.yum_repository:
        name: jenkins
        description: Jenkins-stable
        baseurl: https://pkg.jenkins.io/redhat/jenkins-2.361.3-1.1/jenkins.repo
        enabled: yes
        gpgcheck: 1
        gpgkey: https://pkg.jenkins.io/redhat/jenkins.io.key

    - name: Install Jenkins
      ansible.builtin.dnf:
        name: jenkins
        state: present

    - name: Start and enable Jenkins
      ansible.builtin.service:
        name: jenkins
        state: started
        enabled: true
